"""
AI Subsystem Router.
Provides endpoints for Copilot streaming, PRD generation, Theme Intelligence, and RAG-grounded responses.
"""

import logging
from typing import Any, AsyncGenerator, Dict, Optional
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from app.ai.context_builder import context_builder
from app.core.config import settings
from app.services.gemini import GeminiService

logger = logging.getLogger(__name__)

router = APIRouter(tags=["AI Subsystem"])


# Request Schemas
class CopilotQueryRequest(BaseModel):
    """Incoming query payload from frontend or client."""

    query: str = Field(..., min_length=1, description="User prompt or question")
    prompt_version: Optional[str] = Field(
        default="v1.0", description="Target prompt version"
    )
    analytics_context: Dict[str, Any] = Field(
        default_factory=dict,
        description="Pre-computed analytics KPIs",
    )
    entity_context: Dict[str, Any] = Field(
        default_factory=dict,
        description="Relational database snapshots",
    )


class PRDGenerationRequest(BaseModel):
    feature_name: str = Field(..., example="Automated User Onboarding Flow")
    user_query: str = Field(..., example="Focus on reducing drop-off during step 2")
    category_filter: Optional[str] = Field(None, example="Onboarding")
    limit: int = Field(default=5, ge=1, le=20)


class ThemeIntelligenceRequest(BaseModel):
    cluster_topic: str = Field(..., example="Checkout Payment Gateway Errors")
    category_filter: Optional[str] = Field(None, example="Billing")


async def generate_gemini_stream(
    system_instruction: str, prompt: str
) -> AsyncGenerator[str, None]:
    """
    Asynchronous generator yielding streamed chunks from Groq or Gemini using SSE format.
    """
    try:
        import json
        service = GeminiService()
        combined_prompt = f"System Instruction: {system_instruction}\n\n{prompt}"
        async for token in service.stream_generation(combined_prompt):
            payload = {"content": token}
            yield f"data: {json.dumps(payload)}\n\n"

    except Exception as e:
        logger.error(f"Error during LLM streaming: {str(e)}")
        error_payload = {"error": str(e)}
        yield f"data: [ERROR]: {json.dumps(error_payload)}\n\n"


@router.post(
    "/stream",
    summary="Stream AI Copilot Response over SSE",
    response_class=StreamingResponse,
)
async def stream_copilot_response(request: CopilotQueryRequest):
    """Endpoint for streaming general AI Copilot responses over Server-Sent Events (SSE)."""
    try:
        system_instruction = (
            "You are an expert AI Product Manager Copilot. "
            "Structure your response with clear section headings (##, ###), well-spaced paragraphs, "
            "bulleted lists, bold highlights for metrics, and a concluding '💡 Key Takeaways & Strategic Remarks' section."
        )

        prompt = (
            f"User Query: {request.query}\n\n"
            f"Analytics Context: {request.analytics_context}\n"
            f"Entity Context: {request.entity_context}"
        )

        return StreamingResponse(
            generate_gemini_stream(
                system_instruction=system_instruction,
                prompt=prompt,
            ),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
            },
        )

    except Exception as exc:
        logger.error(f"AI Stream initialization failed: {str(exc)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"AI Stream initialization failed: {str(exc)}",
        )


@router.post(
    "/generate-prd",
    summary="Generate RAG-Grounded PRD (Streaming)",
    description="Streams a Product Requirement Document generated by Groq/Gemini, grounded in vector feedback evidence.",
)
async def generate_prd_endpoint(request: PRDGenerationRequest):
    """Generates PRD with real-time SSE streaming."""
    try:
        context_data = await context_builder.build_prd_prompt(
            feature_name=request.feature_name,
            user_query=request.user_query,
            category_filter=request.category_filter,
            limit=request.limit,
        )

        return StreamingResponse(
            generate_gemini_stream(
                system_instruction=context_data["system_instruction"],
                prompt=context_data["prompt"],
            ),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
                "X-Accel-Buffering": "no",
            },
        )

    except Exception as e:
        logger.error(f"PRD Generation Endpoint Error: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate PRD: {str(e)}",
        )


@router.post(
    "/theme-insights",
    summary="Generate Theme Intelligence Memo",
    description="Analyzes feedback cluster topics and produces strategic recommendations.",
)
async def theme_insights_endpoint(request: ThemeIntelligenceRequest):
    """Generates strategic theme intelligence memo."""
    try:
        context_data = await context_builder.build_theme_intelligence_prompt(
            cluster_topic=request.cluster_topic,
            category_filter=request.category_filter,
        )

        service = GeminiService()
        combined_prompt = f"System Instruction: {context_data['system_instruction']}\n\n{context_data['prompt']}"

        chunks = []
        async for chunk in service.stream_generation(combined_prompt):
            chunks.append(chunk)

        return {
            "status": "success",
            "cluster_topic": request.cluster_topic,
            "evidence_count": context_data["evidence_count"],
            "insights": "".join(chunks),
        }

    except Exception as e:
        logger.error(f"Theme Insights Endpoint Error: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate theme insights: {str(e)}",
        )