"""remove_prd_add_core_models

Revision ID: 0ec45c60979c
Revises: ac6aabb1e9eb
Create Date: 2026-07-26 12:05:26.595451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ec45c60979c'
down_revision: Union[str, None] = 'ac6aabb1e9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_code', sa.String(length=20), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_code', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('estimated_story_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_feature_code'), 'features', ['feature_code'], unique=True)
    op.create_index(op.f('ix_features_project_id'), 'features', ['project_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_code', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=100), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_feedback_code'), 'feedback', ['feedback_code'], unique=True)
    op.create_index(op.f('ix_feedback_project_id'), 'feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sprint_code', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sprint_name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_index(op.f('ix_sprints_sprint_code'), 'sprints', ['sprint_code'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_code', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('ticket_title', sa.String(length=255), nullable=False),
    sa.Column('ticket_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_user_id'), 'tickets', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_project_id'), 'tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_code'), 'tickets', ['ticket_code'], unique=True)
    op.drop_index('ix_feedback_items_feature_request_id', table_name='feedback_items')
    op.drop_index('ix_feedback_items_project_id', table_name='feedback_items')
    op.drop_table('feedback_items')
    op.drop_index('ix_prds_feature_request_id', table_name='prds')
    op.drop_table('prds')
    op.drop_table('feature_requests')
    op.add_column('organizations', sa.Column('organization_code', sa.String(length=20), nullable=False))
    op.add_column('organizations', sa.Column('organization_name', sa.String(length=255), nullable=False))
    op.add_column('organizations', sa.Column('industry', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('organizations', sa.Column('employee_count', sa.Integer(), nullable=False))
    op.add_column('organizations', sa.Column('subscription_plan', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_organizations_organization_code'), 'organizations', ['organization_code'], unique=True)
    op.drop_column('organizations', 'name')
    op.add_column('projects', sa.Column('project_code', sa.String(length=20), nullable=False))
    op.add_column('projects', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('project_name', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('project_type', sa.String(length=100), nullable=False))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('technology_stack', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('budget_usd', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'name')
    op.add_column('workspaces', sa.Column('workspace_code', sa.String(length=20), nullable=False))
    op.add_column('workspaces', sa.Column('workspace_name', sa.String(length=255), nullable=False))
    op.add_column('workspaces', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_workspaces_workspace_code'), 'workspaces', ['workspace_code'], unique=True)
    op.drop_column('workspaces', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_workspaces_workspace_code'), table_name='workspaces')
    op.drop_column('workspaces', 'description')
    op.drop_column('workspaces', 'workspace_name')
    op.drop_column('workspaces', 'workspace_code')
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'budget_usd')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'technology_stack')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'project_name')
    op.drop_column('projects', 'owner_id')
    op.drop_column('projects', 'project_code')
    op.add_column('organizations', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organizations_organization_code'), table_name='organizations')
    op.drop_column('organizations', 'subscription_plan')
    op.drop_column('organizations', 'employee_count')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'organization_name')
    op.drop_column('organizations', 'organization_code')
    op.create_table('feedback_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feature_request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cleaned_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_request_id'], ['feature_requests.id'], name='feedback_items_feature_request_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='feedback_items_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedback_items_pkey')
    )
    op.create_index('ix_feedback_items_project_id', 'feedback_items', ['project_id'], unique=False)
    op.create_index('ix_feedback_items_feature_request_id', 'feedback_items', ['feature_request_id'], unique=False)
    op.create_table('prds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feature_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_markdown', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_request_id'], ['feature_requests.id'], name='prds_feature_request_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='prds_pkey')
    )
    op.create_index('ix_prds_feature_request_id', 'prds', ['feature_request_id'], unique=False)
    op.create_table('feature_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rice_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='feature_requests_pkey')
    )
    op.drop_index(op.f('ix_tickets_ticket_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_project_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_user_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_sprints_sprint_code'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_project_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_code'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_features_project_id'), table_name='features')
    op.drop_index(op.f('ix_features_feature_code'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
