"""add target_audience to projects

Revision ID: 46e4ba205c70
Revises: 2d52d2f79bcd
Create Date: 2026-07-27 22:49:10.224008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46e4ba205c70'
down_revision: Union[str, None] = '2d52d2f79bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('target_audience', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'target_audience')
    # ### end Alembic commands ###
