"""add feedback created at index

Revision ID: 54e536aab78e
Revises: a0b82857cdf7
Create Date: 2026-08-08 17:47:08.323755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e536aab78e'
down_revision: Union[str, None] = 'a0b82857cdf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    # ### end Alembic commands ###
