"""add analytics metrics table

Revision ID: abf429722b14
Revises: 54e536aab78e
Create Date: 2026-08-17 19:25:47.253057

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf429722b14'
down_revision: Union[str, None] = '54e536aab78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_code', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('recorded_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_metrics_metric_code'), 'analytics_metrics', ['metric_code'], unique=True)
    op.create_index(op.f('ix_analytics_metrics_project_id'), 'analytics_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_recorded_date'), 'analytics_metrics', ['recorded_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_metrics_recorded_date'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_project_id'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_metric_code'), table_name='analytics_metrics')
    op.drop_table('analytics_metrics')
    # ### end Alembic commands ###