"""Add foreign key indexes

Revision ID: ac6aabb1e9eb
Revises: 0efceaf02c7d
Create Date: 2026-07-21 18:01:02.775006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6aabb1e9eb'
down_revision: Union[str, None] = '0efceaf02c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedback_items_feature_request_id'), 'feedback_items', ['feature_request_id'], unique=False)
    op.create_index(op.f('ix_feedback_items_project_id'), 'feedback_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_prds_feature_request_id'), 'prds', ['feature_request_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_workspaces_org_id'), 'workspaces', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_org_id'), table_name='workspaces')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_prds_feature_request_id'), table_name='prds')
    op.drop_index(op.f('ix_feedback_items_project_id'), table_name='feedback_items')
    op.drop_index(op.f('ix_feedback_items_feature_request_id'), table_name='feedback_items')
    # ### end Alembic commands ###
